swagger: '2.0'
info:
  title: Thing API
  version: '1'
  description: |
    Example spec for recursion
paths:
  /v1/things:
    get:
      summary: Get a tree of things.
      operationId: getThings
      responses:
        '200':
          description: OK
          schema:
            properties:
              id:
                type: string
                example: an-id
                description: Description of id.
        '400':
          description: Error
          schema:
            properties:
              errorDescription:
                type: string
                example: error message
                description: Explanation of the error
      deprecated: false
